services:
  - type: web
    name: tarimtoptan-api
    runtime: node
    rootDir: Web-Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
