/**
 * Örnek tarım ürünleri — API bağlantısı olmadığında fallback olarak kullanılır.
 * API aktif olduğunda gerçek veriler otomatik olarak bu verilerin yerine geçer.
 */

const sampleProducts = [
    {
        id: 'sample-001',
        name: 'Organik Kırmızı Mercimek',
        description: 'Güneydoğu Anadolu\'nun verimli topraklarında yetiştirilmiş, %100 organik kırmızı mercimek. Protein deposu, çorbalık ve yemeklik olarak kullanılabilir.',
        price: 54.90,
        stock: 320,
        category: 'Bakliyat',
        producerId: 'prod-001',
        createdAt: '2026-03-01T10:00:00Z',
    },
    {
        id: 'sample-002',
        name: 'Osmancık Pirinç (5kg)',
        description: 'Tosya\'nın meşhur Osmancık pirinci. Pilav yapımında en çok tercih edilen, iri taneli ve lezzetli pirinç.',
        price: 189.00,
        stock: 150,
        category: 'Tahıl',
        producerId: 'prod-002',
        createdAt: '2026-03-02T10:00:00Z',
    },
    {
        id: 'sample-003',
        name: 'Doğal Sarı Nohut',
        description: 'Çorum yöresinden toplanan sarı nohut. Kuru yemişlik ve yemeklik olarak ideal. GDO\'suz, katkısız.',
        price: 72.50,
        stock: 200,
        category: 'Bakliyat',
        producerId: 'prod-001',
        createdAt: '2026-03-03T10:00:00Z',
    },
    {
        id: 'sample-004',
        name: 'Köftelik Bulgur (2kg)',
        description: 'Gaziantep usulü ince bulgur. Çiğ köfte, kısır ve salata yapımında mükemmel sonuç verir.',
        price: 42.00,
        stock: 500,
        category: 'Tahıl',
        producerId: 'prod-003',
        createdAt: '2026-03-04T10:00:00Z',
    },
    {
        id: 'sample-005',
        name: 'Organik Domates (1kg)',
        description: 'Antalya seralarında doğal yöntemlerle yetiştirilmiş taze organik domates. Sert, lezzetli, salatalık.',
        price: 34.90,
        stock: 85,
        category: 'Sebze',
        producerId: 'prod-004',
        createdAt: '2026-03-05T10:00:00Z',
    },
    {
        id: 'sample-006',
        name: 'Taze Yeşil Biber (1kg)',
        description: 'Çarliston ve sivri biber karışımı. Taze, çıtır ve aromalı. Kahvaltılık, salataya uygun.',
        price: 29.90,
        stock: 120,
        category: 'Sebze',
        producerId: 'prod-004',
        createdAt: '2026-03-06T10:00:00Z',
    },
    {
        id: 'sample-007',
        name: 'Kuru Fasulye (İspir)',
        description: 'Erzurum İspir\'in dünyaca ünlü kuru fasulyesi. İnce kabuklu, pişirmesi kolay, lezzeti eşsiz.',
        price: 94.00,
        stock: 180,
        category: 'Bakliyat',
        producerId: 'prod-002',
        createdAt: '2026-03-07T10:00:00Z',
    },
    {
        id: 'sample-008',
        name: 'Antep Fıstığı (500g)',
        description: 'Gaziantep\'in dünyaca ünlü yeşil Antep fıstığı. Tatlı yapımı ve atıştırmalık için ideal.',
        price: 249.90,
        stock: 60,
        category: 'Bakliyat',
        producerId: 'prod-003',
        createdAt: '2026-03-08T10:00:00Z',
    },
    {
        id: 'sample-009',
        name: 'Taze Kırmızı Elma (2kg)',
        description: 'Isparta yöresi starking elması. Sert, sulu ve tatlı. Vitamin deposu, doğal meyve.',
        price: 45.00,
        stock: 250,
        category: 'Meyve',
        producerId: 'prod-005',
        createdAt: '2026-03-09T10:00:00Z',
    },
    {
        id: 'sample-010',
        name: 'Organik Bal (850g)',
        description: 'Kaçkar Dağları yaylalarından toplanan süzme çiçek balı. %100 doğal, katkısız.',
        price: 320.00,
        stock: 35,
        category: 'Diğer',
        producerId: 'prod-006',
        createdAt: '2026-03-10T10:00:00Z',
    },
    {
        id: 'sample-011',
        name: 'Yeşil Mercimek (1kg)',
        description: 'Yozgat ovasının bereketli topraklarından yeşil mercimek. Çorba ve salatalar için birebir.',
        price: 62.00,
        stock: 400,
        category: 'Bakliyat',
        producerId: 'prod-001',
        createdAt: '2026-03-11T10:00:00Z',
    },
    {
        id: 'sample-012',
        name: 'Taze Patlıcan (1kg)',
        description: 'Aydın\'ın uzun siyah patlıcanı. Kızartmalık, kebaplık ve dolmalık olarak idealdir.',
        price: 27.50,
        stock: 95,
        category: 'Sebze',
        producerId: 'prod-004',
        createdAt: '2026-03-12T10:00:00Z',
    },
    {
        id: 'sample-013',
        name: 'Ceviz İçi (500g)',
        description: 'Bolu dağ cevizi. Taze kırılmış, iri parçalı iç ceviz. Tatlı ve atıştırmalık için.',
        price: 179.00,
        stock: 70,
        category: 'Bakliyat',
        producerId: 'prod-006',
        createdAt: '2026-03-13T10:00:00Z',
    },
    {
        id: 'sample-014',
        name: 'Trabzon Fındığı (1kg)',
        description: 'Giresun-Ordu yöresinden toplanan tombul fındık. Kavrulmuş ve çiğ seçenekli.',
        price: 210.00,
        stock: 90,
        category: 'Bakliyat',
        producerId: 'prod-006',
        createdAt: '2026-03-14T10:00:00Z',
    },
    {
        id: 'sample-015',
        name: 'Taze Portakal (3kg)',
        description: 'Finike portakalı. İnce kabuklu, bol sulu ve tatlı. Sıkma ve yeme portakalı.',
        price: 39.90,
        stock: 300,
        category: 'Meyve',
        producerId: 'prod-005',
        createdAt: '2026-03-15T10:00:00Z',
    },
    {
        id: 'sample-016',
        name: 'Kuru Kayısı (500g)',
        description: 'Malatya\'nın dünyaca ünlü kuru kayısısı. Güneşte kurutulmuş, katkısız, doğal.',
        price: 89.90,
        stock: 140,
        category: 'Meyve',
        producerId: 'prod-005',
        createdAt: '2026-03-16T10:00:00Z',
    },
]

const sampleProducers = [
    {
        id: 'prod-001',
        name: 'Ege Tarım Kooperatifi',
        email: 'iletisim@egetarim.com',
        phone: '+902321112233',
        address: 'İzmir, Türkiye',
    },
    {
        id: 'prod-002',
        name: 'Karadeniz Organik Çiftlik',
        email: 'info@karadenizorganik.com',
        phone: '+904621234567',
        address: 'Trabzon, Türkiye',
    },
    {
        id: 'prod-003',
        name: 'Güneydoğu Bakliyat A.Ş.',
        email: 'satis@gdbakliyat.com',
        phone: '+903421112233',
        address: 'Gaziantep, Türkiye',
    },
    {
        id: 'prod-004',
        name: 'Akdeniz Sera Tarım',
        email: 'siparis@akdenizsera.com',
        phone: '+902421234567',
        address: 'Antalya, Türkiye',
    },
    {
        id: 'prod-005',
        name: 'Anadolu Meyve Bahçeleri',
        email: 'destek@anadolumeyve.com',
        phone: '+903321234567',
        address: 'Isparta, Türkiye',
    },
    {
        id: 'prod-006',
        name: 'Doğa Ana Organik Gıda',
        email: 'info@dogaana.com',
        phone: '+903741234567',
        address: 'Bolu, Türkiye',
    },
]

export { sampleProducts, sampleProducers }
